[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

from = "/*"
to = "/index.html"
status = 200